name: AWS MyAstroSite Deploy to S3
  
on:
  push:
    branches:
      - main

jobs:
  deploy_to_s3:
    name: deploy astro to s3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup
        run: | 
          npm install
          npm run build
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::058264275313:role/GitHub-ActionsRole"
          role-session-name: github-cd
          aws-region: us-west-1
      
      - name: deploy to s3
        run: aws s3 sync ./dist/ s3://mdcprojects/
      
      - name: invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }}--paths "/*" "/"
