name: Deploy Lambda function
on:
  push:
    paths:
    - 'AWS/Back_End_Code/lambda.py'
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for lambda function
        run: cd AWS/Back_End_Code/lambda.py && zip -r code.zip
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \ --function-name arn:aws:lambda:us-west-1:058264275313:function:visitor-count-boto3-python \--zip-file fileb://AWS/Back_End_Code/code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-1"
